### ISSUE TITLE
loginButton

### ISSUE THREAD

**Issue by martinschenk** [akkaweb/AKKA-CakePHP-Facebook-Plugin#1]
Hi,
thanks for the great plugin.

```
echo $this->Facebook->loginLink($options = []);
```

works perfect out of the box.
But

```
echo $this->Facebook->loginButton($options = []);
```

just makes popup very fast "something" and it doesn't happen any more.

Regards, Martin

**Comment by akkaweb** [comment]
Hello Martin,

Sorry for the delay in responding to this issue. I have been extremely busy with other projects that have kept me away from GitHub. I will test loginButton() and will get back to you.

Thanks for bringing that up.

Regards,
Andre S.

**Comment by martinschenk** [comment]
Hello André 

No problem!
Thanks to you. 

Regards, Martin 

Am 14.07.2015 um 20:25 schrieb AKKA Web Development notifications@github.com:

Hello Martin,

Sorry for the delay in responding to this issue. I have been extremely busy with other projects that have kept me away from GitHub. I will test loginButton() and will get back to you.

Thanks for bringing that up.

Regards,
Andre S.

**Comment by akkaweb** [comment]
After trying several things, I have come to the conclusion that the login button does not work as intended by this plugin. Although I will leave it on here, in case someone is already successfully using it, I will remove the part of the instructions where it details how to install and use the FB Button. Thanks for bringing it up.
