### ISSUE TITLE
AkkaFacebook.GraphComponent could not be found.

### ISSUE THREAD

**Issue by Shiwangi-Gaur** [akkaweb/AKKA-CakePHP-Facebook-Plugin#10]
I am getting the below error in cakephp3.

AkkaFacebook.GraphComponent could not be found. Plugin path is project_title/plugins/AkkaFacebook.
Thanks in advance.

**Comment by akkaweb** [comment]
@Shiwangi-Gaur I need more details of your setup to figure out how you end up with this issue.

**Comment by akkaweb** [comment]
I am assuming you resolved your issue!
