### ISSUE TITLE
Facebook Login Link is not a button

### ISSUE THREAD

**Issue by Theaxiom** [akkaweb/AKKA-CakePHP-Facebook-Plugin#11]
When I use the Facebook login link, I just get a plaintext link to login to Facebook, it is supposed to be a button. How do I make it a button?

**Comment by vhtellez** [comment]
@Theaxiom Did you find a solution?

**Comment by Theaxiom** [comment]
We switched to HybridAuth : https://github.com/ADmad/CakePHP-HybridAuth

**Comment by vhtellez** [comment]
Thank you! 👍
