### ISSUE TITLE
AkkaFacebook.GraphComponent could not be found.

### ISSUE THREAD

**Issue by smartboygauravrai** [akkaweb/AKKA-CakePHP-Facebook-Plugin#12]

**Comment by smartboygauravrai** [comment]
![imgpsh_fullsize](https://cloud.githubusercontent.com/assets/5700211/19885842/d4510948-a046-11e6-999b-2a7a5d520534.jpg)

**Comment by akkaweb** [comment]
Can you make sure the plugin is being loaded?

**Comment by smartboygauravrai** [comment]
Yes i am sure plugin is loaded

**Comment by ramacerratto** [comment]
I dont think that this issue is resolved. I am having the same problem using composer update.
