### ISSUE TITLE
New User Creation

### ISSUE THREAD

**Issue by spacebiscuit** [akkaweb/AKKA-CakePHP-Facebook-Plugin#14]
Thank you for this plugin which is easy to configure and simple to use.

I have a question regarding new User creation when the Facebook.id doesn't match an existing User. I can see that a new password is generated for the User which is randomly generated. How can the User know what the password is, or is a password stored to simply satisfy the User model validation with the ideas being that the User should be able to edit the password if desired?

Further, is it possible to detect when a new User has been created. It would be nice to confirm that a new account has been created/registered (email confirmation to new User) as opposed to a regular login which might just require a flash message.

Thank you in advance.

**Comment by akkaweb** [comment]
Thanks for the feedback!

If Facebook.id does not match an existing/logged in user, the FB Id is added to the user account, but a password is NOT generated nor added at that time. Only the FB ID. The password is only generated and added when a user creates a new account. You are correct, that is only to satisfy the userModel as the user is at this time to login using FB only. However, if the user ever needs that password to login using username/password combination, than your application should provide a Forgot Password link and handle it appropriately.

I am currently developing in the `sdk5` branch which will at some point handle events. Currently that is not provided by default. In the interim, while it is not available in this plugin and if you need it, you could always create an event within your APP to handle `Model.Users.afterSave` or something like that.

There are more details here: https://book.cakephp.org/3.0/en/core-libraries/events.html

**Comment by akkaweb** [comment]
I am assuming this has been resolved.
