### ISSUE TITLE
Class 'Facebook\FacebookSession' not found

### ISSUE THREAD

**Issue by sachindahda** [akkaweb/AKKA-CakePHP-Facebook-Plugin#16]
I have manually downloaded facebook sdk and added the files into vendor/facebook/php-sdk-v4 in cake3.
Can you help me with that?

**Comment by akkaweb** [comment]
I would suggest using composer to install this package so it downloads and correctly sets the Autloads for you. The dev-SDK5 branch requires Facebook SDKv5. You donwloaded Facebook SDKv4.

"facebook/graph-sdk": "^5.0"
