### ISSUE TITLE
Call to a member function getLoginUrl()

### ISSUE THREAD

**Issue by hkosmidi** [akkaweb/AKKA-CakePHP-Facebook-Plugin#2]
I am trying to use your plugin for showing comments on my site.

But I get: 
Fatal Error (1): Call to a member function getLoginUrl() on a non-object in [\vendor\akkaweb\cakephp-facebook\src\Controller\Component\GraphComponent.php, line 351] .

And as I searched there is no such function in Helper. Am I doing something wrong?

**Comment by akkaweb** [comment]
I am not sure if this still applies to you. I was off GitHub for sometime involved in some other projects. If you installed this using Composer, it would most likely pull in the FB library that is required for this plugin to work. The getLoginUrl() is part of that library, not this plugin. Hope that helps.
