### ISSUE TITLE
Fields are empty

### ISSUE THREAD

**Issue by CREAZ-NET** [akkaweb/AKKA-CakePHP-Facebook-Plugin#7]
Hi,

First of all, your plugins looks awesome, 

I'm having issue to make it works ! I tried to use the facebook Login functionnality, i have installed it by Composer and added the following code in AppController.php : 

The plugin seems to works, the session is created but in my users table, the fields first_name, last_name, email and username are empty. I can get the password and the facebook_id. 

Is there anything speciail i have to do in my facebook application ?

Thanks.

<?php
public function initialize(){

```
    parent::initialize();

    $this->loadComponent('AkkaFacebook.Graph', [
        'app_id' => 'i have put the app id here',
        'app_secret' => 'same thing',
        'app_scope' => 'email', // https://developers.facebook.com/docs/facebook-login/permissions/v2.3
        'redirect_url' => Router::url(['controller' => 'Users', 'action' => 'login'], TRUE), // This should be enabled by default
        'post_login_redirect' => '' //ie. Router::url(['controller' => 'Users', 'action' => 'account'], TRUE)
        // 'user_columns' => ['first_name' => 'fname', 'last_name' => 'lname', 'username' => 'uname', 'password' => 'pass'] //not required
    ]);

} 
```

?> 

The authentification is made in my system through the email field instead of the username field, but i have created the username field in case in the table.

'authenticate' => [
                'Form' => [
                    'fields' => ['username' => 'email']
                ]
            ],

**Comment by CREAZ-NET** [comment]
I'm trying to be looged with my french Facebook account, is there any link between this error and that french account ? Do i have to change the language somewhere ?

**Comment by CREAZ-NET** [comment]
In the Helper i have changed us_US by js.src = "//connect.facebook.net/fr_FR/sdk.js"; but still empty fields :)

**Comment by horizon1711** [comment]
I have the same issue. Logged in success but fields are empty.

**Comment by CREAZ-NET** [comment]
I've found why !

In line 243 (GraphComponent)
Replace the line by : 
$this->FacebookRequest = new FacebookRequest($this->FacebookSession, 'GET', '/me?fields=id,first_name,last_name,email');

**Comment by CREAZ-NET** [comment]
Now i'm trying to fix this weird thing at the end of the url,
'#_=_'
I have found out that it comes from FB i just don't know how to fix it.

**Comment by akkaweb** [comment]
Thanks for bringing this up. I will be looking into it shortly.

**Comment by akkaweb** [comment]
`first_name`, `last_name` are public which means they are implied and does not have to be request. If you want to still request them, you can add them to `app_scope` when you load the component. The `#=` is added by Facebook and you might be able to remove it with javascript, however, this only happens when a user logs in.

**Comment by akkaweb** [comment]
https://developers.facebook.com/docs/facebook-login/permissions

**Comment by akkaweb** [comment]
The plugin assumes the following: `

`'user_columns' => [
        'first_name' => 'first_name',
        'last_name' => 'last_name',
        'password' => 'password',
        'username' => 'username'
    ]
`

If your DB fields are different you have to specify them when you load the component. Could you confirm your DB fields are similar to that?

**Comment by akkaweb** [comment]
I have ran several tests and I don't see any issues with that as long as you correctly assign your fields at Component Load as referred in my previous comment. 

This is an example for an application I have that does not use the Plugin's assumed field names:

```
$this->loadComponent('AkkaFacebook.Graph', [
    'app_id' => 'xxxxxxxxxxxxxxxxxxxx',
    'app_secret' => 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'app_scope' => 'email',
    'redirect_url' => Router::url(['controller' => 'Users', 'action' => 'login'], TRUE),
    'post_login_redirect' => Router::url(['controller' => 'Users', 'action' => 'account'], TRUE),
    'user_columns' => ['first_name' => 'fname', 'last_name' => 'lname']
]);
```

Let me know if you are still having issues.
