### ISSUE TITLE
Connection timed

### ISSUE THREAD

**Issue by vaseemkhan** [akkaweb/AKKA-CakePHP-Facebook-Plugin#8]
Connection timed out after 10001 milliseconds

Facebook\FacebookSDKException
@akkaweb

**Comment by akkaweb** [comment]
Hello @vaseemkhan I appreciate your input on this. I have tested it in several of my applications but I dont see this problem. It could be a slow or unavailable connection when you tried. Could you try again and report back? Also, did you install using composer? Regards

**Comment by vaseemkhan** [comment]
Thanks for reply !!
Yes I did install with composer and I have tested it on two different servers in different applications and not found connection related issues.
I have also made changes in ..\vendor\facebook\php-sdk-v4\src\Facebook\HttpClients\FacebookCurlHttpClient.php at line 175 to increase connection time out time but again I got same problem with this message : 

> Connection timed out after **60001/80001** milliseconds
> 
> Facebook\FacebookSDKException

@akkaweb

**Comment by akkaweb** [comment]
Unfortunately this seems to be an issue related to the Facebook Class. After researching online, some people point to an issue with the server making cURL requests. You might have to check that and see if there is anything to be done there.
